#
# Jekyll config file
#

title: 'Les Cabris Explorateurs'

description: >-
  Escalades, grandes voies et randonnées par Alexandra et Benjamin

# Main author of the website
# See > authors.yml
author: bfiorini

# This URL is the main address for absolute links.
# Don't include a slash at the end.
url: 'https://www.cabris-explorateurs.com'
baseurl: ''

# Logo size is 600x80 pixels
# logo: "logo.png"

# Collections
collections:
  routes:
    output: false
    permalink: /voies/:path/
  areas:
    output: true
    permalink: /sites/:path/
  regions:
    output: false
    permalink: /regions/:path/

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  debug: false
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Plugin: AutoPages (jekyll-paginate-v2)
category_base_path: '/blog/category/'
autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - 'autopage_category.html'
    title: ':cat'
    permalink: '/blog/category/:cat'
  collections:
    enabled: false
  tags:
    enabled: false

# Jekyll configuration
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
plugins:
  - jekyll-paginate-v2
  - jekyll-typogrify
  - jekyll-sitemap
  - jekyll-seo-tag
excerpt_separator: "<!--more-->"
source: src
destination: dist
keep_files:
  - assets
include:
  - pages
exclude:
  - _assets

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false

# Plugin: SEO (jekyll-seo-tag)
lang: fr_FR
webmaster_verifications:
  google: 'Ovfyz1x1xQ17V9LNcKdjXG1Qv_JphdbPZYGhSBmg3D0'
#  bing: ''
#  alexa: ''
#  yandex: ''
#  baidu: ''

google_analytics_tracking_id: "UA-115149018-1"

# Front Matter Defaults
defaults:
  - scope:
      path: ''
      type: pages
    values:
      show_meta: false
      title: Les Cabris Explorateurs
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      show_meta: true
      author: alex
  - scope:
      path: ''
      type: areas
    values:
      layout: area
      header: no
      dataTable: true


#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#                                                 More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'
