#
# Jekyll config file
#

title: 'Les Cabris Explorateurs'

# The slogan describes your website and is used on homepage in <title> and other important places
slogan: 'Les cabris explorent'

# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: 'Escalades, grandes voies et randonnées par Alexandra et Benjamin'

# The credits show up in the includes/_footer.html – It would be nice of you to leave a link to Phlow or Feeling Responsive as a thank you :)
credits: '<p>Created with <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>, theme by <a href="http://phlow.de/">Phlow</a>.</p>'


# Main author of the website
# See > authors.yml
author: bfiorini

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'https://www.cabris-explorateurs.com'
baseurl: ''

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: https://github.com/bfiorini/cabris-explorateurs/edit/master

# Logo size is 600x80 pixels
# logo: "logo.png"

# Collections
collections:
  routes:
    output: false
    permalink: /voies/:path:output_ext
  areas:
    output: true
    permalink: /sites/:path:output_ext
  regions:
    output: false
    permalink: /regions/:path:output_ext

# Plugin: Pagination (jekyll-paginate-v2)
pagination:
  enabled: true
  debug: false
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Plugin: AutoPages (jekyll-paginate-v2)
autopages:
  enabled: false

# Jekyll configuration
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
plugins:
  - jekyll-paginate-v2
  - jekyll-typogrify
  - jekyll-sitemap
  - jekyll-seo-tag
excerpt_separator: "<!--more-->"
include:
  - .htaccess
exclude:
  - LICENSE
  - README.md
  - INSTALL.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - yarn.lock
  - gulpfile.babel.js
  - gulp-tasks
  - node_modules
  - .sass-cache
  - netlify.toml
  - _assets
  - images
  - assets/fonts/svg-files-for-custom-font
  - assets/fonts/.fontcustom-manifest.json
  - assets/fonts/fontcustom.yml
  - assets/fonts/iconfont-preview.html

# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false

# Plugin: SEO (jekyll-seo-tag)
lang: fr_FR
webmaster_verifications:
  google: 'Ovfyz1x1xQ17V9LNcKdjXG1Qv_JphdbPZYGhSBmg3D0'
#  bing: ''
#  alexa: ''
#  yandex: ''
#  baidu: ''

google_analytics_tracking_id: "UA-115149018-1"

# Front Matter Defaults
defaults:
  -
    scope:
      path: ''
    values:
      title: Les Cabris Explorateurs
      image:
        featured: /assets/img/header-home-1920.jpg
        cover: true
  -
    scope:
      path: ''
      type: 'pages'
    values:
      show_meta: false
      author: bfiorini
  -
    scope:
      path: _posts
      type: posts
    values:
      layout: post
      show_meta: true
      author: alex
  -
    scope:
      path: ''
      type: routes
    values:
      layout: page
      header: no
      sitemap: false
  -
    scope:
      path: ''
      type: areas
    values:
      layout: area
      header: no


#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#                                                 More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'
