---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: src/_regions
  label: Regions
  create: all
  match: "**/*"
- type: directory
  path: src/_areas
  label: Areas
  create: all
  match: "**/*"
- type: directory
  path: src/_routes
  label: Routes
  create: all
  match: "**/*"
upload_dir: images/cabris-explorateurs
public_path: https://res.cloudinary.com/bfiorini/image/upload
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _dist
  install_dependencies_command: bundle install --path vendor/bundle && npm install
  preview_docker_image: forestryio/ruby:2.6-node10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn build
